# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(259, 183)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame_2)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 1)
        self.Frekvencia_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.Frekvencia_doubleSpinBox.setMinimum(0.0)
        self.Frekvencia_doubleSpinBox.setProperty("value", 0.0)
        self.Frekvencia_doubleSpinBox.setObjectName("Frekvencia_doubleSpinBox")
        self.gridLayout.addWidget(self.Frekvencia_doubleSpinBox, 3, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 3)
        self.Amplituda_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.Amplituda_doubleSpinBox.setMaximum(100000001.0)
        self.Amplituda_doubleSpinBox.setProperty("value", 0.0)
        self.Amplituda_doubleSpinBox.setObjectName("Amplituda_doubleSpinBox")
        self.gridLayout.addWidget(self.Amplituda_doubleSpinBox, 1, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 3)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Apply_pushButton = QtWidgets.QPushButton(self.frame_3)
        self.Apply_pushButton.setObjectName("Apply_pushButton")
        self.horizontalLayout.addWidget(self.Apply_pushButton)
        self.Close_pushButton = QtWidgets.QPushButton(self.frame_3)
        self.Close_pushButton.setObjectName("Close_pushButton")
        self.horizontalLayout.addWidget(self.Close_pushButton)
        self.gridLayout.addWidget(self.frame_3, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Amplituda [mm]"))
        self.label.setText(_translate("Dialog", "Frekvencia[Hz]"))
        self.Apply_pushButton.setText(_translate("Dialog", "Apply"))
        self.Close_pushButton.setText(_translate("Dialog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
